### ISSUE TITLE
TypeError – stack: "TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by NikitaEgorov** [microsoft/PR-Metrics#223]
## Summary

PR Metrics 1.4.2
Version Dev18.M170.6

```
TypeError – stack: "TypeError: Cannot read property 'length' of null\n    at e.forEach (/home/azvmadmin/build_agent_01/_work/_tasks/PRMetrics_907d3b28-6b37-4ac7-ac75-9631ee53e512/1.4.2/index.js:66:130782)\n    at Array.forEach (<anonymous>)\n    at Function.convertPullRequestComments (/home/azvmadmin/build_agent_01/_work/_tasks/PRMetrics_907d3b28-6b37-4ac7-ac75-9631ee53e512/1.4.2/index.js:66:130287)\n    at AzureReposInvoker.getComments (/home/azvmadmin/build_agent_01/_work/_tasks/PRMetrics_907d3b28-6b37-4ac7-ac75-9631ee53e512/1.4.2/index.js:66:127682)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
TypeError – message: "Cannot read property 'length' of null"
```

## Reproduction Steps

```yml

- task: PRMetrics@1
  displayName: PR Metrics
  env:
    PR_METRICS_ACCESS_TOKEN: $(PR_Metrics_Access_Token)
  continueOnError: true

```
