### ISSUE TITLE
Azure Devops token error

### ISSUE THREAD

**Issue by denravonska** [microsoft/PR-Metrics#240]
I'm having some problems getting the generation to work due to token errors. It errors out with:

> "Could not access the resources. Ensure the 'PR_Metrics_Access_Token' secret environment variable has access to 'Code' > 'Read' and 'Pull Request Threads' > 'Read & write'.

I've tried using it both as my own PAT with those credentials, setup as a pipeline secret variable:

```
      - task: PRMetrics@1
        displayName: PR Metrics
        env:
          PR_METRICS_ACCESS_TOKEN: $(PR_Metrics_Access_Token)
        continueOnError: true
```

and by using the, to my knowledge not limited, system access token:
```
      - task: PRMetrics@1
        displayName: PR Metrics
        env:
          PR_METRICS_ACCESS_TOKEN: $(System.AccessToken)
        continueOnError: true
```

Both give the same error. Is there anything else that needs to be done?
