### ISSUE TITLE
Could not access sufficient Git history

### ISSUE THREAD

**Issue by philcart** [microsoft/PR-Metrics#382]
## Summary

Receive error "Could not access sufficient Git history. Add 'fetch-depth: 0' as a parameter to the 'actions/checkout' action." ever after adding fetch-depth parameter.

## Reproduction Steps
Create workflow yaml file as per below. Execute workflow as part of PR status check.
``` yaml
name: PR Metrics
on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
  pull_request_target:
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0
    - name: PR Metrics
      uses: microsoft/PR-Metrics@v1.5.2
      env:
        PR_METRICS_ACCESS_TOKEN: ${{ secrets.PR_METRICS_ACCESS_TOKEN }}
      continue-on-error: true
```

## Additional Information

Repository is private if that has any implications.
