### ISSUE TITLE
Am i possible to use this actions for private (org) repository?

### ISSUE THREAD

**Issue by lucashan13** [microsoft/PR-Metrics#488]
## Summary

I want to use this action on a private (organizational) repository, but the action gets stuck with an "AxiosError: Request failed with status code 404" error, and the problem seems to occur at `https://github.com/{org}/{repo}/pull/{PR number}.diff`. I'm wondering if setting a PAT on PR_METRICS_ACCESS_TOKEN is enough.

## Additional Information

I'm attaching the YML file I set up.

```yml
name: "PR-metric"

permissions:
  pull-requests: write
  statuses: write
  contents: read

env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  pull_request:
    branches:
      - main

jobs:
  pr-metric:
    runs-on: ubuntu-latest
    name: PR Metrics
    env:
      PR_METRICS_ACCESS_TOKEN: ${{ secrets.ORG_GITHUB_PERSONAL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: PR metric
        uses: microsoft/PR-Metrics@v1.5.14
        continue-on-error: true
        with:
          file-matching-patterns: |
            app/src/*
            app/src-server/*
            !app/src-server/context/__generated__/*
            core/src/*
            packages/**/src/*
            studio/*
          code-file-extensions: |
            ts
            tsx
```
